from django.urls import path
from backend_candidate.views import (HomeView,
                                     CompleteMediaNaranjaView,
                                     CandidacyJoinView,
                                     ProfileView,
                                     MyCommitments,
                                     ProposalsForMe,
                                     HelpFindingCandidates,
                                     AddActivityToCandidateView,
                                     MyActivitiesListView,
                                     )
from django.contrib.auth.views import LoginView
from django.views.generic.base import TemplateView

urlpatterns = [
    path('',
            HomeView.as_view(),
            name='home'),
    path('login',
            LoginView.as_view(template_name='backend_candidate/auth_login.html'),
            name='candidate_auth_login'),
    path('profile/<slug:slug>/<slug:candidate_slug>',
            ProfileView.as_view(),
            name='complete_profile'),
    path('media_naranja/<slug:slug>/<slug:candidate_slug>',
            CompleteMediaNaranjaView.as_view(),
            name='complete_12_naranja'),
    path('my_commitments/<slug:slug>/<slug:candidate_slug>',
            MyCommitments.as_view(),
            name='my_proposals_with_a_resolution'),
    path('proposals_for_me/<slug:slug>/<slug:candidate_slug>',
            ProposalsForMe.as_view(),
            name='proposals_for_me'),
    path('candidacy_user_join/<str:identifier>',
            CandidacyJoinView.as_view(),
            name='candidacy_user_join'),
    path('add_activity/<slug:slug>',
            AddActivityToCandidateView.as_view(),
            name='add_activity'),
    path('all_my_activities/<slug:slug>',
            MyActivitiesListView.as_view(),
            name='all_my_activities'),
    path('gracias_totales/',
            TemplateView.as_view(template_name='backend_candidate/thanks_for_commiting.html'),
            name='thanks_for_commiting'),
]
