
from django.urls import path
from backend_staff.views import (
    IndexView,
    PopularProposalCommentsView,
    ModeratePopularProposalView,
    AcceptPopularProposalView,
    RejectPopularProposalView,
    AddContactAndSendMailView,
    AllCommitmentsView,
    StatsView,
    ListOfUsers,
    StatsPerAreaView,
)

urlpatterns = [
    path('',
        IndexView.as_view(),
        name='index'),
    path('stats/',
        StatsView.as_view(),
        name='stats'),
    path('per_area_stats/',
        StatsPerAreaView.as_view(),
        name='per_area_stats'),
    path('popular_proposal_comments/<int:pk>/',
        PopularProposalCommentsView.as_view(),
        name='popular_proposal_comments'),
    path('moderate_popular_proposal/<int:pk>/',
        ModeratePopularProposalView.as_view(),
        name='moderate_proposal'),
    path('accept_popular_proposal/<int:pk>/',
        AcceptPopularProposalView.as_view(),
        name='accept_proposal'),
    path('reject_popular_proposal/<int:pk>/',
        RejectPopularProposalView.as_view(),
        name='reject_proposal'),
    path('add_contact_and_sen_mail/<int:pk>/',
        AddContactAndSendMailView.as_view(),
        name='add_contact_and_send_mail'),
    path('all_commitments/',
        AllCommitmentsView.as_view(),
        name='all_commitments'),
    path('list_of_users/',
        ListOfUsers.as_view(),
        name='list_of_users'),
]
