from django.urls import path
from popular_proposal.views.proposal_views import (ProposalCreationView,
                                                   ThanksForProposingView,
                                                   SubscriptionView,
                                                   HomeView,
                                                   PopularProposalDetailView,
                                                   PopularProposalUpdateView,
                                                   UnlikeProposalView,
                                                   ProposalsPerArea,
                                                   CommitView,
                                                   NotCommitView,
                                                   CommitmentDetailView,
                                                   PopularProposalOGImageView,
                                                   PopularProposalDetailRedirectView,
                                                   PopularProposalAyuranosView,
                                                   )
from popular_proposal.views.wizard import (ProposalWizard,
                                           ProposalWizardFull,
                                           ProposalWizardFullWithoutArea,
                                           wizard_creator_chooser)
from django.views.decorators.clickjacking import xframe_options_exempt
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    path('',
        HomeView.as_view(),
        name='home'),
    path('embedded',
        xframe_options_exempt(HomeView.as_view(is_embedded=True)),
        name='embedded_home'),
    path('area_embedded/<slug:slug>',
        ProposalsPerArea.as_view(is_embedded=True),
        name='area_embedded'),
    path('create_wizard/<slug:slug>',
        ProposalWizard.as_view(),
        name='propose_wizard'),
    path('nueva',
        ProposalWizardFull.as_view(),
        name='propose_wizard_full'),
    path('crear',
        wizard_creator_chooser().as_view(),
        name='propose_wizard_full_without_area'),
    path('detail/<slug:slug>',
        xframe_options_exempt(PopularProposalDetailView.as_view()),
        name='detail'),
    path('ayudanos/<slug:slug>',
        PopularProposalAyuranosView.as_view(),
        name='ayuranos'),
    path('d/<int:pk>',
        PopularProposalDetailRedirectView.as_view(),
        name='short_detail'),
    path('og_image/<slug:slug>.jpg',
        PopularProposalOGImageView.as_view(),
        name='og_image'),
    path('commitment/<slug:candidate_slug>/<slug:proposal_slug>',
        CommitmentDetailView.as_view(),
        name='commitment'),
    path('commit/<int:candidate_pk>/<int:proposal_pk>',
        CommitView.as_view(),
        name='commit_yes'),
    path('not_commit/<int:candidate_pk>/<int:proposal_pk>',
        NotCommitView.as_view(),
        name='commit_no'),
    path('embedded_detail/<slug:slug>',
        xframe_options_exempt(PopularProposalDetailView.as_view(is_embedded=True)),
        name='embedded_detail'),
    path('unlike/<int:pk>',
        UnlikeProposalView.as_view(),
        name='unlike_proposal'),
    path('actualizar/<slug:slug>',
        PopularProposalUpdateView.as_view(),
        name='citizen_update'),
    path('<slug:slug>',
        ProposalCreationView.as_view(),
        name='propose'),
    path('<int:pk>/gracias',
        ThanksForProposingView.as_view(),
        name='thanks'),
    path('<int:pk>/subscribe',
        SubscriptionView.as_view(),
        name='like_a_proposal'),
]
